#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CoffeeManagerAdmin.Droid.Resource", IsApplication=true)]

namespace CoffeeManagerAdmin.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Droid.Support.V7.AppCompat.Resource.Id.add = global::CoffeeManagerAdmin.Droid.Resource.Id.add;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.ApplicationName = global::CoffeeManagerAdmin.Droid.Resource.String.ApplicationName;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.Hello = global::CoffeeManagerAdmin.Droid.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int sections = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int accent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activated_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int black = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int colorAccent = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int colorPrimary = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int colorPrimary20Opaque = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int colorPrimaryDark = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int colorPrimary_text = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int colorSecondary_text = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int darkGrayishBlue = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int divider = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int grayishCyan = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int lightPrimary = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int primary = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int primaryDark = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int primaryText = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int secondaryText = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int tabtext_color_selector = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int textIcon = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int white = 2130837523;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int app_bar_height = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int app_bar_height_collapsed = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int base_cell_height = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int base_icon_size = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int drawer_width = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int fontSize10 = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int margin_huge = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int margin_large = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int margin_medium = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int margin_small = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int margin_tinier = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int margin_tiny = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int page_indicator_default_size = 2130903052;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040001
			public const int expenses_tab_selector = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int finance_tab_selector = 2130968578;
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			// aapt resource value: 0x7F040003
			public const int ic_account_circle_black_24dp = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ic_add_circle_outline_white_24dp = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int ic_arrow_back_white_24dp = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ic_arrow_upward_black_24dp = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int ic_attach_money_black_24dp = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ic_credit_card_black_24dp = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ic_local_cafe_black_24dp = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ic_save_white_24dp = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ic_settings_black_24dp = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ic_shopping_basket_black_24dp = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int ic_trending_up_black_24dp = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int products_tab_selector = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int statistic_tab_selector = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int storage_tab_selector = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int take_cup_transparent = 2130968593;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int add = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int amount = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int card = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int content_frame = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int currency = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int currency_text = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int date = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int earned = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int expenses = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int home_tab_layout = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int home_viewpager = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int is_active_checkbox = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int main_view_pager_holder = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int name = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int name_edit_text = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int name_text = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int payment_on_store_text = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int read_shift = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int real_amount = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int recyclerview_cashout = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int recyclerview_earnings = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int recyclerview_penalties = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int recyclerview_shifts = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int recyclerview_stores = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int recyclerview_users = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int salary_text = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int save = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int select_store_button = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int shift = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int store_name = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int tab_icon = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int tab_title = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int toolbar = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int toolbar_layout = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int user = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int user_expense_text = 2131034147;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int item_columns = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070001
			public const int credit_card = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int credit_card_cashout_header = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int credit_card_cashout_item = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int fragment_expenses = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int fragment_finance = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int fragment_products = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int fragment_statistic = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int fragment_store = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int login = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int main = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int penalty_item = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int settings = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int shift_info_header = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int shift_info_item = 2131165198;
			
			// aapt resource value: 0x7F070000
			public const int SplashScreen = 2131165184;
			
			// aapt resource value: 0x7F07000F
			public const int store_item = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int tab_item_main = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int toolbar = 2131165201;
			
			// aapt resource value: 0x7F070017
			public const int users = 2131165207;
			
			// aapt resource value: 0x7F070012
			public const int user_detail = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int user_earnings = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int user_earnings_header = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int user_earnings_item = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int user_item = 2131165206;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F080000
			public const int main_menu = 2131230720;
			
			// aapt resource value: 0x7F080002
			public const int users_menu = 2131230722;
			
			// aapt resource value: 0x7F080001
			public const int user_details_menu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int ic_launcher = 2131296256;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0003
			public const int add = 2131361795;
			
			// aapt resource value: 0x7F0A0005
			public const int address = 2131361797;
			
			// aapt resource value: 0x7F0A0004
			public const int add_store = 2131361796;
			
			// aapt resource value: 0x7F0A0006
			public const int amount = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int amount_to_salary_pay = 2131361799;
			
			// aapt resource value: 0x7F0A0000
			public const int ApplicationName = 2131361792;
			
			// aapt resource value: 0x7F0A0008
			public const int card = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int cashout = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int cashout_action = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int cashout_history = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public const int credit_card_money = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public const int currency = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int current_balance = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int current_salary = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public const int current_shift_money = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public const int date = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public const int day_percent = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public const int earned_amount = 2131361811;
			
			// aapt resource value: 0x7F0A0014
			public const int email = 2131361812;
			
			// aapt resource value: 0x7F0A0015
			public const int entire_money = 2131361813;
			
			// aapt resource value: 0x7F0A0016
			public const int entire_salary = 2131361814;
			
			// aapt resource value: 0x7F0A0017
			public const int expenses = 2131361815;
			
			// aapt resource value: 0x7F0A0018
			public const int expenses_tab_title = 2131361816;
			
			// aapt resource value: 0x7F0A0019
			public const int finance_tab_title = 2131361817;
			
			// aapt resource value: 0x7F0A0001
			public const int Hello = 2131361793;
			
			// aapt resource value: 0x7F0A001A
			public const int login = 2131361818;
			
			// aapt resource value: 0x7F0A001B
			public const int minimun_payment = 2131361819;
			
			// aapt resource value: 0x7F0A001C
			public const int name = 2131361820;
			
			// aapt resource value: 0x7F0A0002
			public const int Navigation = 2131361794;
			
			// aapt resource value: 0x7F0A001D
			public const int night_percent = 2131361821;
			
			// aapt resource value: 0x7F0A001E
			public const int password = 2131361822;
			
			// aapt resource value: 0x7F0A0020
			public const int payment = 2131361824;
			
			// aapt resource value: 0x7F0A0022
			public const int payments = 2131361826;
			
			// aapt resource value: 0x7F0A0021
			public const int payment_on_store = 2131361825;
			
			// aapt resource value: 0x7F0A001F
			public const int pay_salary = 2131361823;
			
			// aapt resource value: 0x7F0A0023
			public const int penalties = 2131361827;
			
			// aapt resource value: 0x7F0A0024
			public const int penalty = 2131361828;
			
			// aapt resource value: 0x7F0A0025
			public const int products_tab_title = 2131361829;
			
			// aapt resource value: 0x7F0A0026
			public const int real_amount = 2131361830;
			
			// aapt resource value: 0x7F0A0027
			public const int real_shift = 2131361831;
			
			// aapt resource value: 0x7F0A0028
			public const int refresh = 2131361832;
			
			// aapt resource value: 0x7F0A0029
			public const int save = 2131361833;
			
			// aapt resource value: 0x7F0A002A
			public const int select = 2131361834;
			
			// aapt resource value: 0x7F0A002B
			public const int settings = 2131361835;
			
			// aapt resource value: 0x7F0A002C
			public const int shift = 2131361836;
			
			// aapt resource value: 0x7F0A002D
			public const int shifts_title = 2131361837;
			
			// aapt resource value: 0x7F0A002E
			public const int statistic_tab_title = 2131361838;
			
			// aapt resource value: 0x7F0A002F
			public const int store = 2131361839;
			
			// aapt resource value: 0x7F0A0031
			public const int stores = 2131361841;
			
			// aapt resource value: 0x7F0A0030
			public const int store_tab_title = 2131361840;
			
			// aapt resource value: 0x7F0A0035
			public const int users = 2131361845;
			
			// aapt resource value: 0x7F0A0032
			public const int user_detail = 2131361842;
			
			// aapt resource value: 0x7F0A0033
			public const int user_expense = 2131361843;
			
			// aapt resource value: 0x7F0A0034
			public const int user_name = 2131361844;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int ActionBarTheme = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int AppTheme = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int AppTheme_AppBarOverlay = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int AppTheme_NoActionBar = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int AppTheme_PopupOverlay = 2131427332;
			
			// aapt resource value: 0x7F0B0007
			public const int borderles_button = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int button = 2131427336;
			
			// aapt resource value: 0x7F0B0005
			public const int SplashTheme = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int ToolbarTheme = 2131427334;
			
			// aapt resource value: 0x7F0B0009
			public const int toolbar_global = 2131427337;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
