//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> ExpenseType { get; set; }
        public Nullable<int> CoffeeRoomNo { get; set; }
    
        public virtual ExpenseType ExpenseType1 { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
