//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuplyRequest
    {
        public int Id { get; set; }
        public int SuplyProductId { get; set; }
        public int ItemCount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool IsDone { get; set; }
    
        public virtual SupliedProduct SupliedProduct { get; set; }
    }
}
