//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuplyOrderItem
    {
        public int Id { get; set; }
        public Nullable<int> SuplyOrderId { get; set; }
        public Nullable<int> SuplyProductId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public bool IsDone { get; set; }
        public int CoffeeRoomNo { get; set; }
    
        public virtual SupliedProduct SupliedProduct { get; set; }
        public virtual SuplyOrder SuplyOrder { get; set; }
    }
}
