//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoOrdersHistory
    {
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int CoffeeRoomId { get; set; }
        public int OrderId { get; set; }
    
        public virtual AutoOrder AutoOrder { get; set; }
        public virtual CoffeeRoom CoffeeRoom { get; set; }
    }
}
