//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnabledCoffeeCounter
    {
        public int Id { get; set; }
        public int CounterId { get; set; }
        public bool IsEnabled { get; set; }
        public int CoffeeRoomNo { get; set; }
    
        public virtual CoffeeCounterForCoffeeRoom CoffeeCounterForCoffeeRoom { get; set; }
        public virtual CoffeeRoom CoffeeRoom { get; set; }
    }
}
