//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseSuplyProduct
    {
        public int Id { get; set; }
        public int ExpenseId { get; set; }
        public int SuplyProductId { get; set; }
        public decimal Amount { get; set; }
        public decimal Quantity { get; set; }
        public int CoffeeRoonNo { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual SupliedProduct SupliedProduct { get; set; }
    }
}
