//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expense()
        {
            this.Users = new HashSet<User>();
            this.ExpenseSuplyProducts = new HashSet<ExpenseSuplyProduct>();
        }
    
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> ExpenseType { get; set; }
        public Nullable<int> CoffeeRoomNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool IsUserSalaryPayment { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ExpenseType ExpenseType1 { get; set; }
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseSuplyProduct> ExpenseSuplyProducts { get; set; }
        public virtual User User { get; set; }
    }
}
