//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReportItem
    {
        public int Id { get; set; }
        public int CoffeeRoomNo { get; set; }
        public int InventoryReportId { get; set; }
        public int SuplyProductId { get; set; }
        public decimal QuantityBefore { get; set; }
        public decimal QuantityAfter { get; set; }
        public decimal QuantityDiff { get; set; }
    
        public virtual InventoryReport InventoryReport { get; set; }
        public virtual SupliedProduct SupliedProduct { get; set; }
    }
}
