//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Sales = new HashSet<Sale>();
            this.SupliedProducts = new HashSet<SupliedProduct>();
            this.ProductCalculations = new HashSet<ProductCalculation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProductType { get; set; }
        public decimal Price { get; set; }
        public decimal PolicePrice { get; set; }
        public Nullable<int> CoffeeRoomNo { get; set; }
        public Nullable<int> CupType { get; set; }
        public Nullable<int> SuplyProductId { get; set; }
        public bool IsActive { get; set; }
        public bool IsSaleByWeight { get; set; }
        public bool Removed { get; set; }
        public int CategoryId { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
    
        public virtual CupType CupType1 { get; set; }
        public virtual ProductType ProductType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupliedProduct> SupliedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCalculation> ProductCalculations { get; set; }
        public virtual Category Category { get; set; }
    }
}
