//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupliedProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupliedProduct()
        {
            this.ProductCalculations = new HashSet<ProductCalculation>();
            this.SuplyOrderItems = new HashSet<SuplyOrderItem>();
            this.ExpenseSuplyProducts = new HashSet<ExpenseSuplyProduct>();
            this.InventoryReportItems = new HashSet<InventoryReportItem>();
            this.UtilizedSuplyProducts = new HashSet<UtilizedSuplyProduct>();
            this.SuplyProductQuantities = new HashSet<SuplyProductQuantity>();
            this.CoffeeCounters = new HashSet<CoffeeCounter>();
            this.CoffeeCounterForCoffeeRooms = new HashSet<CoffeeCounterForCoffeeRoom>();
            this.SuplyProductOrderItems = new HashSet<SuplyProductOrderItem>();
            this.SuplyProductAutoOrdersHistories = new HashSet<SuplyProductAutoOrdersHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ExprenseTypeId { get; set; }
        public bool Removed { get; set; }
        public bool InventoryEnabled { get; set; }
        public string ExpenseNumerationName { get; set; }
        public decimal ExpenseNumerationMultyplier { get; set; }
        public string InventoryNumerationName { get; set; }
        public decimal InventoryNumerationMultyplier { get; set; }
    
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCalculation> ProductCalculations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuplyOrderItem> SuplyOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseSuplyProduct> ExpenseSuplyProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryReportItem> InventoryReportItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilizedSuplyProduct> UtilizedSuplyProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuplyProductQuantity> SuplyProductQuantities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoffeeCounter> CoffeeCounters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoffeeCounterForCoffeeRoom> CoffeeCounterForCoffeeRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuplyProductOrderItem> SuplyProductOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuplyProductAutoOrdersHistory> SuplyProductAutoOrdersHistories { get; set; }
    }
}
