//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedCupsPerShift
    {
        public int Id { get; set; }
        public int ShiftId { get; set; }
        public int C110 { get; set; }
        public int C170 { get; set; }
        public int C250 { get; set; }
        public int C400 { get; set; }
        public int Plastic { get; set; }
        public int CoffeeRoomNo { get; set; }
    
        public virtual Shift Shift { get; set; }
    }
}
