//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPaymentStrategy
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CoffeeRoomId { get; set; }
        public decimal DayShiftPersent { get; set; }
        public decimal NightShiftPercent { get; set; }
        public decimal SimplePayment { get; set; }
        public decimal MinimumPayment { get; set; }
    
        public virtual CoffeeRoom CoffeeRoom { get; set; }
        public virtual User User { get; set; }
    }
}
