//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Shifts = new HashSet<Shift>();
            this.UserPenalties = new HashSet<UserPenalty>();
            this.UserEarningsHistories = new HashSet<UserEarningsHistory>();
            this.Expenses = new HashSet<Expense>();
            this.UserPaymentStrategies = new HashSet<UserPaymentStrategy>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CoffeeRoomNo { get; set; }
        public bool IsActive { get; set; }
        public decimal CurrentEarnedAmount { get; set; }
        public decimal EntireEarnedAmount { get; set; }
        public Nullable<int> ExpenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift> Shifts { get; set; }
        public virtual Expense Expense { get; set; }
        public virtual ExpenseType ExpenseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPenalty> UserPenalties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEarningsHistory> UserEarningsHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense> Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPaymentStrategy> UserPaymentStrategies { get; set; }
    }
}
