//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeManager.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilizedSuplyProduct
    {
        public int Id { get; set; }
        public int SuplyProductId { get; set; }
        public int ShiftId { get; set; }
        public decimal Quantity { get; set; }
        public string Reason { get; set; }
        public System.DateTime Date { get; set; }
        public int CoffeeRoomNo { get; set; }
    
        public virtual Shift Shift { get; set; }
        public virtual SupliedProduct SupliedProduct { get; set; }
    }
}
